from cat import Car
bmw = Car("KA013060",5)
bmw.start()
bmw.start()
bmw.change_gear()
bmw.change_gear()
bmw.change_gear()
bmw.change_gear()
bmw.change_gear()
bmw.change_gear()
bmw.stop()
bmw.change_gear()